include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint

linter:
  rules:
    prefer_final_in_for_each: true
    prefer_final_locals: true
    always_use_package_imports: true
    prefer_single_quotes: true
