class Country {
  final String name;
  final String iso;

  const Country({required this.name, required this.iso});

  factory Country.fromIso(String iso) {
    return countries.singleWhere((country) {
      return country.iso == iso.toUpperCase();
    });
  }
}

final countries = [
  Country(name: 'Afghanistan', iso: 'AF'),
  Country(name: 'Albania', iso: 'AL'),
  Country(name: 'Algeria', iso: 'DZ'),
  Country(name: 'American Samoa', iso: 'AS'),
  Country(name: 'Andorra', iso: 'AD'),
  Country(name: 'Angola', iso: 'AO'),
  Country(name: 'Anguilla', iso: 'AI'),
  Country(name: 'Antarctica', iso: 'AQ'),
  Country(name: 'Antigua and Barbuda', iso: 'AG'),
  Country(name: 'Argentina', iso: 'AR'),
  Country(name: 'Armenia', iso: 'AM'),
  Country(name: 'Aruba', iso: 'AW'),
  Country(name: 'Australia', iso: 'AU'),
  Country(name: 'Austria', iso: 'AT'),
  Country(name: 'Azerbaijan', iso: 'AZ'),
  Country(name: 'Bahamas (the)', iso: 'BS'),
  Country(name: 'Bahrain', iso: 'BH'),
  Country(name: 'Bangladesh', iso: 'BD'),
  Country(name: 'Barbados', iso: 'BB'),
  Country(name: 'Belarus', iso: 'BY'),
  Country(name: 'Belgium', iso: 'BE'),
  Country(name: 'Belize', iso: 'BZ'),
  Country(name: 'Benin', iso: 'BJ'),
  Country(name: 'Bermuda', iso: 'BM'),
  Country(name: 'Bhutan', iso: 'BT'),
  Country(name: 'Bolivia (Plurinational State of)', iso: 'BO'),
  Country(name: 'Bonaire, Sint Eustatius and Saba', iso: 'BQ'),
  Country(name: 'Bosnia and Herzegovina', iso: 'BA'),
  Country(name: 'Botswana', iso: 'BW'),
  Country(name: 'Bouvet Island', iso: 'BV'),
  Country(name: 'Brazil', iso: 'BR'),
  Country(name: 'British Indian Ocean Territory (the)', iso: 'IO'),
  Country(name: 'Brunei Darussalam', iso: 'BN'),
  Country(name: 'Bulgaria', iso: 'BG'),
  Country(name: 'Burkina Faso', iso: 'BF'),
  Country(name: 'Burundi', iso: 'BI'),
  Country(name: 'Cabo Verde', iso: 'CV'),
  Country(name: 'Cambodia', iso: 'KH'),
  Country(name: 'Cameroon', iso: 'CM'),
  Country(name: 'Canada', iso: 'CA'),
  Country(name: 'Cayman Islands (the)', iso: 'KY'),
  Country(name: 'Central African Republic (the)', iso: 'CF'),
  Country(name: 'Chad', iso: 'TD'),
  Country(name: 'Chile', iso: 'CL'),
  Country(name: 'China', iso: 'CN'),
  Country(name: 'Christmas Island', iso: 'CX'),
  Country(name: 'Cocos (Keeling) Islands (the)', iso: 'CC'),
  Country(name: 'Colombia', iso: 'CO'),
  Country(name: 'Comoros (the)', iso: 'KM'),
  Country(name: 'Congo (the Democratic Republic of the)', iso: 'CD'),
  Country(name: 'Congo (the)', iso: 'CG'),
  Country(name: 'Cook Islands (the)', iso: 'CK'),
  Country(name: 'Costa Rica', iso: 'CR'),
  Country(name: 'Croatia', iso: 'HR'),
  Country(name: 'Cuba', iso: 'CU'),
  Country(name: 'Curaçao', iso: 'CW'),
  Country(name: 'Cyprus', iso: 'CY'),
  Country(name: 'Czechia', iso: 'CZ'),
  Country(name: 'Côte d\'Ivoire', iso: 'CI'),
  Country(name: 'Denmark', iso: 'DK'),
  Country(name: 'Djibouti', iso: 'DJ'),
  Country(name: 'Dominica', iso: 'DM'),
  Country(name: 'Dominican Republic (the)', iso: 'DO'),
  Country(name: 'Ecuador', iso: 'EC'),
  Country(name: 'Egypt', iso: 'EG'),
  Country(name: 'El Salvador', iso: 'SV'),
  Country(name: 'Equatorial Guinea', iso: 'GQ'),
  Country(name: 'Eritrea', iso: 'ER'),
  Country(name: 'Estonia', iso: 'EE'),
  Country(name: 'Eswatini', iso: 'SZ'),
  Country(name: 'Ethiopia', iso: 'ET'),
  Country(name: 'Falkland Islands (the) [Malvinas]', iso: 'FK'),
  Country(name: 'Faroe Islands (the)', iso: 'FO'),
  Country(name: 'Fiji', iso: 'FJ'),
  Country(name: 'Finland', iso: 'FI'),
  Country(name: 'France', iso: 'FR'),
  Country(name: 'French Guiana', iso: 'GF'),
  Country(name: 'French Polynesia', iso: 'PF'),
  Country(name: 'French Southern Territories (the)', iso: 'TF'),
  Country(name: 'Gabon', iso: 'GA'),
  Country(name: 'Gambia (the)', iso: 'GM'),
  Country(name: 'Georgia', iso: 'GE'),
  Country(name: 'Germany', iso: 'DE'),
  Country(name: 'Ghana', iso: 'GH'),
  Country(name: 'Gibraltar', iso: 'GI'),
  Country(name: 'Greece', iso: 'GR'),
  Country(name: 'Greenland', iso: 'GL'),
  Country(name: 'Grenada', iso: 'GD'),
  Country(name: 'Guadeloupe', iso: 'GP'),
  Country(name: 'Guam', iso: 'GU'),
  Country(name: 'Guatemala', iso: 'GT'),
  Country(name: 'Guernsey', iso: 'GG'),
  Country(name: 'Guinea', iso: 'GN'),
  Country(name: 'Guinea-Bissau', iso: 'GW'),
  Country(name: 'Guyana', iso: 'GY'),
  Country(name: 'Haiti', iso: 'HT'),
  Country(name: 'Heard Island and McDonald Islands', iso: 'HM'),
  Country(name: 'Holy See (the)', iso: 'VA'),
  Country(name: 'Honduras', iso: 'HN'),
  Country(name: 'Hong Kong', iso: 'HK'),
  Country(name: 'Hungary', iso: 'HU'),
  Country(name: 'Iceland', iso: 'IS'),
  Country(name: 'India', iso: 'IN'),
  Country(name: 'Indonesia', iso: 'ID'),
  Country(name: 'Iran (Islamic Republic of)', iso: 'IR'),
  Country(name: 'Iraq', iso: 'IQ'),
  Country(name: 'Ireland', iso: 'IE'),
  Country(name: 'Isle of Man', iso: 'IM'),
  Country(name: 'Israel', iso: 'IL'),
  Country(name: 'Italy', iso: 'IT'),
  Country(name: 'Jamaica', iso: 'JM'),
  Country(name: 'Japan', iso: 'JP'),
  Country(name: 'Jersey', iso: 'JE'),
  Country(name: 'Jordan', iso: 'JO'),
  Country(name: 'Kazakhstan', iso: 'KZ'),
  Country(name: 'Kenya', iso: 'KE'),
  Country(name: 'Kiribati', iso: 'KI'),
  Country(name: 'Korea (the Democratic People\'s Republic of)', iso: 'KP'),
  Country(name: 'Korea (the Republic of)', iso: 'KR'),
  Country(name: 'Kosovo', iso: 'XK'),
  Country(name: 'Kuwait', iso: 'KW'),
  Country(name: 'Kyrgyzstan', iso: 'KG'),
  Country(name: 'Lao People\'s Democratic Republic (the)', iso: 'LA'),
  Country(name: 'Latvia', iso: 'LV'),
  Country(name: 'Lebanon', iso: 'LB'),
  Country(name: 'Lesotho', iso: 'LS'),
  Country(name: 'Liberia', iso: 'LR'),
  Country(name: 'Libya', iso: 'LY'),
  Country(name: 'Liechtenstein', iso: 'LI'),
  Country(name: 'Lithuania', iso: 'LT'),
  Country(name: 'Luxembourg', iso: 'LU'),
  Country(name: 'Macao', iso: 'MO'),
  Country(name: 'Madagascar', iso: 'MG'),
  Country(name: 'Malawi', iso: 'MW'),
  Country(name: 'Malaysia', iso: 'MY'),
  Country(name: 'Maldives', iso: 'MV'),
  Country(name: 'Mali', iso: 'ML'),
  Country(name: 'Malta', iso: 'MT'),
  Country(name: 'Marshall Islands (the)', iso: 'MH'),
  Country(name: 'Martinique', iso: 'MQ'),
  Country(name: 'Mauritania', iso: 'MR'),
  Country(name: 'Mauritius', iso: 'MU'),
  Country(name: 'Mayotte', iso: 'YT'),
  Country(name: 'Mexico', iso: 'MX'),
  Country(name: 'Micronesia (Federated States of)', iso: 'FM'),
  Country(name: 'Moldova (the Republic of)', iso: 'MD'),
  Country(name: 'Monaco', iso: 'MC'),
  Country(name: 'Mongolia', iso: 'MN'),
  Country(name: 'Montenegro', iso: 'ME'),
  Country(name: 'Montserrat', iso: 'MS'),
  Country(name: 'Morocco', iso: 'MA'),
  Country(name: 'Mozambique', iso: 'MZ'),
  Country(name: 'Myanmar', iso: 'MM'),
  Country(name: 'Namibia', iso: 'NA'),
  Country(name: 'Nauru', iso: 'NR'),
  Country(name: 'Nepal', iso: 'NP'),
  Country(name: 'Netherlands (the)', iso: 'NL'),
  Country(name: 'New Caledonia', iso: 'NC'),
  Country(name: 'New Zealand', iso: 'NZ'),
  Country(name: 'Nicaragua', iso: 'NI'),
  Country(name: 'Niger (the)', iso: 'NE'),
  Country(name: 'Nigeria', iso: 'NG'),
  Country(name: 'Niue', iso: 'NU'),
  Country(name: 'Norfolk Island', iso: 'NF'),
  Country(name: 'Northern Mariana Islands (the)', iso: 'MP'),
  Country(name: 'Norway', iso: 'NO'),
  Country(name: 'Oman', iso: 'OM'),
  Country(name: 'Pakistan', iso: 'PK'),
  Country(name: 'Palau', iso: 'PW'),
  Country(name: 'Palestine, State of', iso: 'PS'),
  Country(name: 'Panama', iso: 'PA'),
  Country(name: 'Papua New Guinea', iso: 'PG'),
  Country(name: 'Paraguay', iso: 'PY'),
  Country(name: 'Peru', iso: 'PE'),
  Country(name: 'Philippines (the)', iso: 'PH'),
  Country(name: 'Pitcairn', iso: 'PN'),
  Country(name: 'Poland', iso: 'PL'),
  Country(name: 'Portugal', iso: 'PT'),
  Country(name: 'Puerto Rico', iso: 'PR'),
  Country(name: 'Qatar', iso: 'QA'),
  Country(name: 'Republic of North Macedonia', iso: 'MK'),
  Country(name: 'Romania', iso: 'RO'),
  Country(name: 'Russian Federation (the)', iso: 'RU'),
  Country(name: 'Rwanda', iso: 'RW'),
  Country(name: 'Réunion', iso: 'RE'),
  Country(name: 'Saint Barthélemy', iso: 'BL'),
  Country(name: 'Saint Helena, Ascension and Tristan da Cunha', iso: 'SH'),
  Country(name: 'Saint Kitts and Nevis', iso: 'KN'),
  Country(name: 'Saint Lucia', iso: 'LC'),
  Country(name: 'Saint Martin (French part)', iso: 'MF'),
  Country(name: 'Saint Pierre and Miquelon', iso: 'PM'),
  Country(name: 'Saint Vincent and the Grenadines', iso: 'VC'),
  Country(name: 'Samoa', iso: 'WS'),
  Country(name: 'San Marino', iso: 'SM'),
  Country(name: 'Sao Tome and Principe', iso: 'ST'),
  Country(name: 'Saudi Arabia', iso: 'SA'),
  Country(name: 'Senegal', iso: 'SN'),
  Country(name: 'Serbia', iso: 'RS'),
  Country(name: 'Seychelles', iso: 'SC'),
  Country(name: 'Sierra Leone', iso: 'SL'),
  Country(name: 'Singapore', iso: 'SG'),
  Country(name: 'Sint Maarten (Dutch part)', iso: 'SX'),
  Country(name: 'Slovakia', iso: 'SK'),
  Country(name: 'Slovenia', iso: 'SI'),
  Country(name: 'Solomon Islands', iso: 'SB'),
  Country(name: 'Somalia', iso: 'SO'),
  Country(name: 'South Africa', iso: 'ZA'),
  Country(name: 'South Georgia and the South Sandwich Islands', iso: 'GS'),
  Country(name: 'South Sudan', iso: 'SS'),
  Country(name: 'Spain', iso: 'ES'),
  Country(name: 'Sri Lanka', iso: 'LK'),
  Country(name: 'Sudan (the)', iso: 'SD'),
  Country(name: 'Suriname', iso: 'SR'),
  Country(name: 'Svalbard and Jan Mayen', iso: 'SJ'),
  Country(name: 'Sweden', iso: 'SE'),
  Country(name: 'Switzerland', iso: 'CH'),
  Country(name: 'Syrian Arab Republic', iso: 'SY'),
  Country(name: 'Taiwan (Province of China)', iso: 'TW'),
  Country(name: 'Tajikistan', iso: 'TJ'),
  Country(name: 'Tanzania, United Republic of', iso: 'TZ'),
  Country(name: 'Thailand', iso: 'TH'),
  Country(name: 'Timor-Leste', iso: 'TL'),
  Country(name: 'Togo', iso: 'TG'),
  Country(name: 'Tokelau', iso: 'TK'),
  Country(name: 'Tonga', iso: 'TO'),
  Country(name: 'Trinidad and Tobago', iso: 'TT'),
  Country(name: 'Tunisia', iso: 'TN'),
  Country(name: 'Turkey', iso: 'TR'),
  Country(name: 'Turkmenistan', iso: 'TM'),
  Country(name: 'Turks and Caicos Islands (the)', iso: 'TC'),
  Country(name: 'Tuvalu', iso: 'TV'),
  Country(name: 'Uganda', iso: 'UG'),
  Country(name: 'Ukraine', iso: 'UA'),
  Country(name: 'United Arab Emirates (the)', iso: 'AE'),
  Country(
    name: 'United Kingdom of Great Britain and Northern Ireland (the)',
    iso: 'GB',
  ),
  Country(name: 'United States Minor Outlying Islands (the)', iso: 'UM'),
  Country(name: 'United States of America (the)', iso: 'US'),
  Country(name: 'Uruguay', iso: 'UY'),
  Country(name: 'Uzbekistan', iso: 'UZ'),
  Country(name: 'Vanuatu', iso: 'VU'),
  Country(name: 'Venezuela (Bolivarian Republic of)', iso: 'VE'),
  Country(name: 'Viet Nam', iso: 'VN'),
  Country(name: 'Virgin Islands (British)', iso: 'VG'),
  Country(name: 'Virgin Islands (U.S.)', iso: 'VI'),
  Country(name: 'Wallis and Futuna', iso: 'WF'),
  Country(name: 'Western Sahara', iso: 'EH'),
  Country(name: 'Yemen', iso: 'YE'),
  Country(name: 'Zambia', iso: 'ZM'),
  Country(name: 'Zimbabwe', iso: 'ZW'),
  Country(name: 'Åland Islands', iso: 'AX'),
];
